<a href="https://colab.research.google.com/github/ng-quys/DeepLearning/blob/main/bt_tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
sinh mảng sô thực [0, 1]

In [1]:
import numpy as np

# Sinh ngẫu nhiên mảng số thực [0, 1]
a = np.random.rand(5)
print("Random 1-D array\n", a)

b = np.random.rand(3, 4)
print("Random 2-D array\n", b)

c = np.random.rand(3, 4, 3)
print("Random 3-D array\n", c)

Random 1-D array
 [0.14902698 0.26818889 0.66062115 0.94272955 0.29598985]
Random 2-D array
 [[0.48551148 0.94835236 0.13691835 0.33688056]
 [0.56772851 0.71711686 0.46717589 0.75860974]
 [0.02435585 0.73126996 0.08690647 0.2869494 ]]
Random 3-D array
 [[[0.4301118  0.98809339 0.89943747]
  [0.72908529 0.95217427 0.7693683 ]
  [0.24433421 0.34938187 0.39906207]
  [0.97826419 0.15065909 0.38158189]]

 [[0.92847896 0.99056877 0.42948341]
  [0.04659227 0.65993724 0.98474766]
  [0.83688646 0.49400953 0.9857944 ]
  [0.873187   0.63589709 0.21862249]]

 [[0.58378618 0.58120954 0.4604986 ]
  [0.66832001 0.31775107 0.73884136]
  [0.4055184  0.08498438 0.36039585]
  [0.09477174 0.14701243 0.74134972]]]


In [ ]:
sinh mảng số nguyên ngẫu nhiên

In [ ]:
import numpy as np

# Sinh mảng 1 chiều gồm 5 số nguyên ngẫu nhiên từ 0 -> 99
a = np.random.randint(100, size=(5,))
print("Random 1-D array\n", a)

# Sinh mảng 2 chiều 3 hàng 4 cột
b = np.random.randint(100, size=(3, 4))
print("Random 2-D array\n", b)

# Sinh mảng 3 chiều kích thước 3x4x3 (3 khối, mỗi khối có 4 hàng, mỗi hàng có 3 cột)
c = np.random.randint(100, size=(3, 4, 3))
print("Random 3-D array\n", c)

In [ ]:
#3.5.2. Platten là chuyển array nhiều chiều về 1 chiều

In [ ]:
import numpy as np

e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()    # flatten() dùng để trải phẳng mảng
print(f)

g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]])

j = g.flatten()
print(j)

In [ ]:
# 3.6. Thêm dòng dữ liệu với hstack và vstack

In [ ]:
import numpy as np

f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])

h_stack = np.hstack((f, g))    # hstack là nối theo chiều ngang
print("Horizontal Append\n", h_stack)

v_stack = np.vstack((f, g))   # vstack là nối theo chiều dọc
print("Vertical Append\n", v_stack)

In [ ]:
# thay đổi kích thước ma trận

In [ ]:
import numpy as np

# Mảng 2 chiều
e = np.array([[1., 2., 3.],
              [4., 5., 6.]])

print(e)
print(e.shape)

# Đổi từ (2,3) -> (3,2)
f = e.reshape(3, 2)
print(f)

# Mảng 3 chiều
g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])

print(g)
print(g.shape)

# reshape thành 3 hàng 4 cột
h = g.reshape(3, 4)
print("reshape (3,4)\n", h)

# reshape thành 3 khối, 2 hàng, 2 cột
j = g.reshape(3, 2, 2)
print("reshape (3,2,2)\n", j)

# reshape thành 2 khối, 3 hàng, 2 cột
k = g.reshape(2, 3, 2)
print("reshape (2,3,2)\n", k)